name: mobile_owner
description: "JelloMark Owner - Beauty Shop Management Platform"
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  equatable: ^2.0.8
  dartz: ^0.10.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.3.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  mocktail: ^1.0.4
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  fonts:
    - family: Esamanru
      fonts:
        - asset: assets/fonts/esamanru-Light.ttf
          weight: 300
        - asset: assets/fonts/esamanru-Medium.ttf
          weight: 500
        - asset: assets/fonts/esamanru-Bold.ttf
          weight: 700
